server {
    server_name 13.209.105.93;

    listen 80;
    client_max_body_size 10M;
    resolver 127.0.0.11 ipv6=off valid=30s;
    set $fastapi_upstream "fastapi:8000";

    # 추후 certbot ssl 인증서 갱신 시 필요
    location /.well-known/acme-challenge/ {
       root /var/www/certbot;
    }

    location /api/ {
        proxy_pass http://$fastapi_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
