server {
    server_name care-bridge.site;

    listen 80;

    # 추후 certbot ssl 인증서 갱신 시 필요
    location /.well-known/acme-challenge/ {
       root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    server_name care-bridge.site;

    listen 443 ssl;

    client_max_body_size 10M;
    resolver 127.0.0.11 ipv6=off valid=30s;
    set $fastapi_upstream "http://fastapi:8000";


    # SSL 인증서 (Let's Encrypt에서 발급된 인증서)
    ssl_certificate /etc/letsencrypt/live/care-bridge.site/fullchain.pem;

    # SSL 개인 키
    ssl_certificate_key /etc/letsencrypt/live/care-bridge.site/privkey.pem;

    # certbot이 제공하는 권장 SSL 설정
    # TLS 보안 설정 포함 (cipher, protocol 등)
    include /etc/letsencrypt/options-ssl-nginx.conf;

    # Diffie-Hellman 키, TLS handshake 보안을 강화
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /api/ {
        proxy_pass http://$fastapi_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
